#pragma config(Sensor, dgtl1,  LeftBackEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  LeftFrontEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  ,               sensorTouch)
#pragma config(Sensor, dgtl6,  ,               sensorTouch)
#pragma config(Sensor, dgtl7,  ,               sensorTouch)
#pragma config(Sensor, dgtl8,  ,               sensorTouch)
#pragma config(Sensor, dgtl9,  RightFrontEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl11, RightBackEncoder, sensorQuadEncoder)
#pragma config(Motor,  port1,           LeftBackTop,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port2,           LeftBackBottom, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           LeftFront,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           ExtraOne,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           ExtraTwo,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           RightFront,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           RightBackBottom, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port10,          RightBackTop,  tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Utility.c";


void autonomousprogram()
{


}



void automove(int angle, int distance)
{


}
