#pragma config(Sensor, dgtl1,  LeftBackEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  LeftFrontEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  ,               sensorTouch)
#pragma config(Sensor, dgtl6,  ,               sensorTouch)
#pragma config(Sensor, dgtl7,  ,               sensorTouch)
#pragma config(Sensor, dgtl8,  ,               sensorTouch)
#pragma config(Sensor, dgtl9,  RightFrontEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl11, RightBackEncoder, sensorQuadEncoder)
#pragma config(Motor,  port1,           LeftBackTop,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port2,           LeftBackBottom, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           LeftFront,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           ExtraOne,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           ExtraTwo,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           RightFront,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           RightBackBottom, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port10,          RightBackTop,  tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Utility.c";


task main()
{
  while(1)
  {
    bool mecanum = false;
    int power[] =  {0, 0, 0, 0, 0, 0};
    //EXPANDING OUTWARDS
    if (vexRT(Btn7U))
    {
      power[RF] = -127;
      power[RB] = 127;
      power[LF] = -127;
      power[LB] = 127;
    }
    //EXPANDING INWARDS
    else if (vexRT(Btn7D))
    {
      power[RF] = 127;
      power[RB] = -127;
      power[LF] = 127;
      power[LB] = -127;
    }
    else
    {
      MecanumDrive();
      mecanum = true;
    }

    if (vexRT(Btn8U) )
    {
      power[EX1] = 127;
    }
    else if (vexRT(Btn8D))
    {
      power[EX1] = -127;
    }

    if (vexRT(Btn8L))
    {
      power[EX2] = -127;
    }
    else if (vexRT(Btn8R))
    {
      power[EX2] = 127;
    }

    if (vexRT(Btn6U))
    {
      power[EX1] = power[EX2] = 127;
    }
    else if (vexRT(Btn6D))
    {
      power[EX1] = power[EX2] = -127;
    }

    if (!mecanum)
    {
      for(int i = 0; i < 6; i++)
      {
        move(i, power[i]);
      }
    }
  }
}
